[project]
name = "cifutils"
version = "0.1.0"
requires-python = "==3.8.19"
dependencies = [
    "django==2.2",
    "jinja2==3.0.3",
    "prettyconf==2.2.1",
    "xlsxwriter==3.0.3",
]

[dependency-groups]
dev = ["ipython>=8.12.3", "pytest>=8.3.5"]
prod = ["gunicorn>=23.0.0"]
